Kernel360/KDEV3-unsemawang-BE

- src/main/java/com/palbang/unsemawang/community/repository/PostRepositoryCustomImpl.java
[Fix] 게시글 목록 조회 시 중복 수정
#210 
1. `findPopularPosts` 중복 글 제거:
- 기존 커서 조건이 `popularityScore`(조회수와 좋아요 수를 조합한 점수)와 정확하게 연동되지 않아 중복 글이 발생.
- 커서 조건을 수정하여 동일 점수를 가진 데이터에서도 중복이 발생하지 않도록 설정.
2. `isCursorForPopular` 메서드 추가:
- `popularityScore`(`viewCount * 7 + likeCount * 3`)와 `id`를 기반으로 커서를 계산하는 메서드 추가.
- 점수가 낮은 경우 및 점수가 동일한 경우 ID를 기준으로 페이징이 올바르게 동작하도록 수정.
3. `findPopularPosts` 메서드 리팩토링:
- 새로운 `isCursorForPopular` 메서드를 적용하여 커서 조건 강화 및 중복 제거.
- 정렬 조건(`popularityScore.desc(), id.desc()`)과 조건이 일치하도록 정비.
> [Fix] 게시글 목록 조회 시 중복 수정

- src/main/java/com/palbang/unsemawang/chemistry/constant/ChemistryCalculator.java
- src/main/java/com/palbang/unsemawang/chemistry/constant/FiveElements.java
- src/main/java/com/palbang/unsemawang/common/constants/ResponseCode.java
- src/test/java/com/palbang/unsemawang/chemistry/constant/ChemistryCalculatorTest.java
- 궁합 매칭 점수 계산 기능
- #214
- 궁합 매칭 점수 테스트 코드 추가
- 상생/상극/일간합 관계 양방향 조회 가능하게 수정
- 양방향 관계를 위해 `Map<String, String>`에서 `Map<String, Set<String>>`으로 변경
- 점수를 직접 넣었는데 상수로 다 바꾼 후에 refactor 이슈로 다시 pr 날리겠습니다... 지금은 다른거 해야해서욥..
> [Feat] 궁합 매칭 점수 계산 기능 #214

- src/main/java/com/palbang/unsemawang/chemistry/entity/MemberMatchingScore.java
- 엔티티 위치 수정
- #226
- 
- 패키지 위치 수정
> [Fix] MemberMatchingScore Entity 패키지 위치 수정 #226

- build.gradle
- src/main/java/com/palbang/unsemawang/config/RedisConfig.java
- src/main/resources/application.properties
- src/test/java/com/palbang/unsemawang/config/EmbeddedRedisConfig.java
- src/test/resources/application.properties
**레디스 기본 환경 세팅**
- Closed #229 
- 레디스 연결을 위한 기본적인 Config 클래스 및 프로퍼티 값 추가
- 테스트용 임베디드 redis Config 클래스 추가
.
.
> [Feature] 레디스 기본 환경 세팅 #229

- .gitignore
- build.gradle
- src/main/java/com/palbang/unsemawang/config/FirebaseConfig.java
- src/main/java/com/palbang/unsemawang/fcm/constant/BrowserType.java
- src/main/java/com/palbang/unsemawang/fcm/constant/DeviceType.java
- src/main/java/com/palbang/unsemawang/fcm/controller/FcmController.java
- src/main/java/com/palbang/unsemawang/fcm/dto/request/FcmNotificationRequest.java
- src/main/java/com/palbang/unsemawang/fcm/dto/request/FcmTokenRegiRequest.java
- src/main/java/com/palbang/unsemawang/fcm/entity/FcmToken.java
- src/main/java/com/palbang/unsemawang/fcm/repository/FcmRepository.java
- src/main/java/com/palbang/unsemawang/fcm/service/FcmService.java
- 알림 기능 구현을 위해 FCM 기능 추가
- #225 
1)
bulid.gradle
```
implementation 'com.google.firebase:firebase-admin:9.4.3'
```
Firebase Admin SDK를 의존성(Dependency)으로 추가하는 코드
★서버 반영시 리눅스 서버에 환경변수 추가 필요 FCM 인증서( .json 파일 위치)
★ vapidKey FCM토큰 요청시 필요
★ 로직상 수정할 사항 이 있지만 fcm 알림 테스트 하기 위해 이렇게 반영
> [Feat] FCM 기능 추가

- src/main/java/com/palbang/unsemawang/config/FirebaseConfig.java
fcm config 수정 
- #225 
serviceAccountKey.json 파일 읽어오는 방법 수정
ClassPathResource를 사용해서 파일 읽어옴
```
ClassPathResource resource = new ClassPathResource("firebase/serviceAccountKey.json");
```
> fix: fcm config 수정

- src/main/java/com/palbang/unsemawang/config/FirebaseConfig.java
fix:fcm 임시 주석
- #255 
fix:fcm 임시 주석 서버 구동 안되서 임시 주석 처리했습니다.
주요 변경된 코드나 함수, 클래스, 모듈에 대해 설명해 주세요. 변경 사항이 중요한 부분이라면 코드와 함께 설명을 추가해주세요.
> fix:fcm 임시 주석

- src/main/java/com/palbang/unsemawang/config/FirebaseConfig.java
일시 주석했던 소스 주석해제
- #225 
docker-compose 파일 변경해서 잘 되는지 테스트하기 위함
> fix:config 주석해제

- src/main/java/com/palbang/unsemawang/config/FirebaseConfig.java
fcm의 .json 파일 환경에 따라 다르게 동작하도록 수정
- #225 
fcm의 .json 파일 환경에 따라 다르게 동작하도록 수정
> fix: cofing 컨테이너와 로컬환경에 따라 다르게 동작

- src/main/java/com/palbang/unsemawang/common/constants/ResponseCode.java
- src/main/java/com/palbang/unsemawang/config/FirebaseConfig.java
- src/main/java/com/palbang/unsemawang/fcm/controller/FcmController.java
- src/main/java/com/palbang/unsemawang/fcm/dto/request/FcmNotificationRequest.java
- src/main/java/com/palbang/unsemawang/fcm/repository/FcmRepository.java
- src/main/java/com/palbang/unsemawang/fcm/service/FcmService.java
fcm토큰 조회 및 삭제
- #274 
1. fcm 토큰 조회 및 삭제 api 구현
2. FcmNotificationRequest 수정 => 링크url 추가
3. fcm 메세지에 image 추가
4. fcm config 수정
```
else {
firebaseApp = FirebaseApp.getInstance();
log.info("FirebaseApp already initialized");
}
```
이미 초기화된 경우엔 기존 객체 FirebaseApp 가져오도록 수정
> [Feat]:fcm토큰 조회 및 삭제

- src/main/java/com/palbang/unsemawang/activity/aop/ActivityTraceAspect.java
주석처리 하였습니다.
- #279 
주석처리 하였습니다.
> fix:aop 수정(주석처리)

- src/main/java/com/palbang/unsemawang/chat/controller/ChatController.java
- src/main/java/com/palbang/unsemawang/chat/controller/ChatRoomController.java
- src/main/java/com/palbang/unsemawang/chat/dto/ChatMessageDto.java
- src/main/java/com/palbang/unsemawang/chat/service/ChatMessageConsumer.java
- src/main/java/com/palbang/unsemawang/chat/service/ChatMessageProducer.java
- src/main/java/com/palbang/unsemawang/chat/service/ChatRoomService.java
- src/main/java/com/palbang/unsemawang/config/RabbitMQConfig.java
- src/main/java/com/palbang/unsemawang/config/WebSocketConfig.java
- src/main/java/com/palbang/unsemawang/config/security/SecurityConfig.java
[Fix] 예외처리 수정
#287 
1. 로깅 간소화
- 불필요한 디버그 로그 제거
2. `GeneralException` 적용
3. `ChatRoomController`의 `/chat/user-status/{userId}` 엔드포인트 삭제
- 사용자 상태관리 기능 존재 X
4. `WebSocketConfig`, `RabbitMQConfig` 위치 변경
5. `ChatRoomService`의 채팅방 목록 조회, 채팅방 나가기의 내부 로직 메서드로 분리
```java
/**
* 채팅방에서 사용자를 제거하는 메서드
*/
private boolean removeUserFromChatRoom(ChatRoom chatRoom, String userId, boolean isUser1) {
if (isUser1 && chatRoom.getUser1() != null && chatRoom.getUser1().getId().equals(userId)) {
chatRoom.setUser1(null);
return true;
} else if (!isUser1 && chatRoom.getUser2() != null && chatRoom.getUser2().getId().equals(userId)) {
chatRoom.setUser2(null);
return true;
}
return false;
}
/**
* 채팅방에서 대상 사용자를 찾는 메서드
*/
private Optional<Member> getTargetUser(ChatRoom chatRoom, String userId) {
if (chatRoom.getUser1() …
```
> [Fix] 채팅 클래스 예외처리 수정

- src/test/java/com/palbang/unsemawang/activity/repository/ActiveMemberRepositoryTest.java
**문제가 되는 테스트코드 주석 처리**
- Closed #291 
- 임베디드 레디스가 제대로 동작하지 않아 제대로 공부하고 적용해보겠습니다...
- 그때까진 문제가 되는 테스트코드 주석 처리하겠습니다!!
.
> [Fix] 문제가 되는 테스트코드 주석 처리 #291

- src/main/java/com/palbang/unsemawang/common/util/pagination/LongCursorResponse.java
- src/main/java/com/palbang/unsemawang/community/dto/response/PostListResponse.java
- src/main/java/com/palbang/unsemawang/community/service/MyCommunityService.java
- src/main/java/com/palbang/unsemawang/community/service/PostListService.java
- Post 커서 페이징 오류 수정
- #277 
- 게시글 목록 조회에서 다음 페이지가 없음에도 hasNext가 true로 나옴 -> 수정
- 레디스 저장 후 조회만 실패
> [Fix] Post 커서 페이징 오류 수정 #277

- src/main/java/com/palbang/unsemawang/config/RabbitMQConfig.java
- src/main/resources/application.properties
[Fix] rabitmq 설정 테스트
#306
1. application.properties의 rabbitmq 호스트 수정 테스트
```
spring.rabbitmq.listener.simple.auto-startup=true
spring.rabbitmq.listener.simple.default-requeue-rejected=false
spring.rabbitmq.template.exchange=chat.exchange
spring.rabbitmq.template.routing-key=chat.routing.key
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
```
> [Bug] rabbutmq 설정 추가

- src/main/java/com/palbang/unsemawang/chat/constant/SenderType.java
**[작업 내용을 간략히 적어주세요]**
이 PR이 해결하는 문제나 관련된 이슈 번호를 작성해 주세요. 예시: #123, #456
이번 PR에서 어떤 변경이 있었는지 간단히 설명해 주세요.
예를 들어, 버그 수정, 새로운 기능 추가, 리팩토링 등.
주요 변경된 코드나 함수, 클래스, 모듈에 대해 설명해 주세요. 변경 사항이 중요한 부분이라면 코드와 함께 설명을 추가해주세요.
> Fix: SenderType 수정

- src/main/java/com/palbang/unsemawang/chat/dto/ChatMessageDto.java
[Fix] SenderType @JsonProperty 적용
#311
[Fix] SenderType @JsonProperty 적용
[Fix] SenderType @JsonProperty 적용
> [Fix] SenderType @JsonProperty 적용

- src/main/java/com/palbang/unsemawang/chat/constant/SenderType.java
- src/main/java/com/palbang/unsemawang/chat/controller/ChatController.java
- src/main/java/com/palbang/unsemawang/chat/dto/ChatMessageDto.java
- src/main/java/com/palbang/unsemawang/chat/service/ChatMessageConsumer.java
- src/main/java/com/palbang/unsemawang/chat/service/ChatMessageProducer.java
[Fix] 채팅 저장 후 발행, 구독
#311
[Fix] 채팅 저장 후 발행, 구독
[Fix] 채팅 저장 후 발행, 구독
> [Fix] 채팅 저장 후 발행, 구독

- src/main/java/com/palbang/unsemawang/chat/service/ChatRoomService.java
**[작업 내용을 간략히 적어주세요]**
이 PR이 해결하는 문제나 관련된 이슈 번호를 작성해 주세요. 예시: #123, #456
이번 PR에서 어떤 변경이 있었는지 간단히 설명해 주세요.
예를 들어, 버그 수정, 새로운 기능 추가, 리팩토링 등.
주요 변경된 코드나 함수, 클래스, 모듈에 대해 설명해 주세요. 변경 사항이 중요한 부분이라면 코드와 함께 설명을 추가해주세요.
> [Fix] SenderType 주석처리

- src/main/java/com/palbang/unsemawang/chat/dto/ChatRoomDto.java
- src/main/java/com/palbang/unsemawang/chat/dto/response/ChatHistoryReadResponse.java
- src/main/java/com/palbang/unsemawang/chat/entity/ChatRoom.java
- src/main/java/com/palbang/unsemawang/chat/entity/MessageStatus.java
- src/main/java/com/palbang/unsemawang/chat/repository/ChatRoomRepository.java
- src/main/java/com/palbang/unsemawang/chat/service/ChatRoomService.java
[Fix] 채팅방 나가기 수정
#318
1. `ChatRoom` Entity 클래스에 `user1Out`, `user2Out` 필드 추가
- 기존 `null` 값 주입 로직으로 채팅방 목록 조회 시 `nullPointException` 발생으로 목록 조회 불가능
- `user1Out`, `user2Out` 필드 추가 후 채팅방 목록 필터링으로 목록 조회 수정
> [Fix] 채팅방 나가기 수정

- src/main/java/com/palbang/unsemawang/chat/repository/ChatMessageRepository.java
- src/main/java/com/palbang/unsemawang/chat/service/ChatRoomService.java
[Fix] 시스템 메세지 출력 수정
#318
[Fix] 시스템 메세지 출력 수정
[Fix] 시스템 메세지 출력 수정
> [Fix] 시스템 메세지 출력 수정

- src/main/java/com/palbang/unsemawang/member/dto/SignupExtraInfoRequest.java
- src/main/java/com/palbang/unsemawang/member/dto/request/UpdateMemberRequest.java
- src/main/java/com/palbang/unsemawang/member/entity/Member.java
- src/main/java/com/palbang/unsemawang/member/service/MemberService.java
회원 매칭 허용 여부 컬럼 추가
- #302 
회원 매칭 허용 여부 컬럼 추가에 따른 엔티티, SignExtraInfoRequest(DTO) 수정
> [feat] 회원 매칭허용여부 추가

- src/main/java/com/palbang/unsemawang/config/WebSocketConfig.java
**heartbeat 주기 변경**
- Closed #326
- 웹소켓 heartbeat 주기를 25초에서 10초로 변경하였습니다
- 이유: 25초는 서로의 접속 상태를 실시간으로 알기에 너무 느리다는 의견이 있어 10초로 줄였습니다
.
.
> [Fix] heartbeat 주기 변경

- src/main/java/com/palbang/unsemawang/chat/service/ChatRoomService.java
[Fix] 채팅방 최신 메세지 순으로 정렬
#311
1. 채팅방 최신 메세지 순으로 정렬
```java
.sorted((dto1, dto2) -> dto2.getLastChatTime().compareTo(dto1.getLastChatTime()))
.collect(Collectors.toList());
```
> [Fix] 채팅방 최신 메세지 순으로 정렬

- src/main/java/com/palbang/unsemawang/chat/controller/ChatController.java
- src/main/java/com/palbang/unsemawang/chat/dto/NewChatMessageDto.java
- src/main/java/com/palbang/unsemawang/chat/repository/ChatMessageRepository.java
- src/main/java/com/palbang/unsemawang/chat/service/ChatMessageConsumer.java
- src/main/java/com/palbang/unsemawang/chat/service/ChatMessageService.java
**rabbitMQ 사용 로직 임시 제거**
브랜치와 이슈가 안맞지만 급한 관계로 바로 수정했습니다.. 
- rabbitMQ의 사용으로 새로운 메세지 처리 속도가 늦어져 임시 제거 했습니다
- 하는김에 새로운 메세지 보낼 때 시간도 같이 전달하도록 DTO 수정했습니답,,
- 하는 김에 서비스 로직 분리좀 했습니다 ㅎㅎ..
.
> [Fix] rabbitMQ 사용 로직 임시 제거 #326

- src/main/java/com/palbang/unsemawang/chat/entity/ChatRoom.java
[Fix] ChatRoom 엔티티 Column name 어노테이션 추가
#311
1. `ChatRoom` Entity 클래스에 `@Column(name = "column_name", nullable = false)` 추가
> [Fix] ChatRoom 엔티티 Column name 어노테이션 추가

- src/main/java/com/palbang/unsemawang/chat/controller/ChatController.java
- src/main/java/com/palbang/unsemawang/chat/service/ChatMessageService.java
채팅 메시지 전송시 알림 보내도록 기능 추가
- #330 
채팅 메시지 전송시 알림 보내도록 기능 추가
우선 알림 동의한 상태에게 메시지 알림 보내도록 수정하였습니다.
해당 채팅방을 보고 있는 사용자에게는 알림 보내지 않도록 수정할 예정
> [Feat] 채팅 메시지 전송시 알림 보내도록 기능 추가

- src/main/java/com/palbang/unsemawang/member/dto/MemberProfileDto.java
- src/main/java/com/palbang/unsemawang/member/entity/Member.java
- src/main/java/com/palbang/unsemawang/member/service/MemberService.java
- src/main/java/com/palbang/unsemawang/oauth2/service/CustomOAuth2UserService.java
Member 엔티티 수정
- #302 
OAuth 신규 회원가입 안되는 문제 발생으로 수정
DB에 isDeleted 와 is_deleted 컬럼 두개가 생겨겨서 isDeleted 컬럼 삭제하였음
name ="is_deleted" 추가 
@Column(name ="is_deleted",nullable = false)
@Builder.Default
private Boolean isDeleted = false;
> [Fix] Member 엔티티 수정

- src/main/java/com/palbang/unsemawang/common/util/file/entity/File.java
- src/main/java/com/palbang/unsemawang/common/util/file/service/FileService.java
- src/main/java/com/palbang/unsemawang/common/util/file/service/FileServiceImpl.java
- src/main/java/com/palbang/unsemawang/common/util/file/service/S3Service.java
**[File 유틸에서 presigned URL 제외, CloudFront 추가 및 코드 개선]**
#323
이번 PR에서 어떤 변경이 있었는지 간단히 설명해 주세요.
예를 들어, 버그 수정, 새로운 기능 추가, 리팩토링 등.
S3Service
- presigned URL 대신 CloudFront를 경유하도록 수정
- 객체 key 구조를 조금 더 직관적이고 인덱싱 분포도 좋도록 수정
FileServiceImpl
- getFileUrl, getFileUrls 메서드를 공유하도록 수정
- 파일이 없다고 runtime 예외가 발생하지 않도록 수정 (필요 시 개별 메서드 추가하기)
File, FileServiceImpl
- 접근제한 레벨 추가
> [Refactor] File 유틸에서 presigned URL 제외, CloudFront 추가 및 코드 개선 #323

- src/main/java/com/palbang/unsemawang/member/dto/request/UpdateMemberRequest.java
- src/main/java/com/palbang/unsemawang/member/entity/Member.java
- src/main/java/com/palbang/unsemawang/member/service/MemberService.java
매치동의여부 버그수정
- #302 
매치동의여부 변경 및 조회 안되는 문제 수정
> [Fix] 매치동의여부 버그수정
