Kernel360/KDEV3-unsemawang-BE

- src/main/java/com/palbang/unsemawang/community/dto/response/PostDetailResponse.java
- src/main/java/com/palbang/unsemawang/community/repository/PostRepositoryCustomImpl.java
- src/main/java/com/palbang/unsemawang/community/service/PostDetailService.java
Fix: 게시글 검색 버그 수정, 게시글 상세조회 응답 memberid 삭제
1. `PostRepositoryCustomImpl` 의 게시글 검색(`buildSearchCondition`) 수정
2. `PostDetailResponse`의 `memberId` 필드 삭제
1. `PostRepositoryCustomImpl` 의 게시글 검색(`buildSearchCondition`) 수정
- 기존 코드의 익명 글 제외 조건이 모든 익명게시글을 제외
- 작성자가 '익명'인 경우만 제외하도록 수정
2. `PostDetailResponse`의 `memberId` 필드 삭제
- 게시글 상세조회 시 익명인 경우에도 `memberId` 필드가 노출되어 삭제함
> [Fix] 게시글 검색 버그 수정, 게시글 상세조회 응답 memberid 삭제

- src/main/java/com/palbang/unsemawang/member/controller/MemberController.java
- src/main/java/com/palbang/unsemawang/member/dto/SignupExtraInfoRequest.java
- src/test/java/com/palbang/unsemawang/member/controller/MemberControllerTest.java
**미래의 생년월일 회원가입 안되도록 검증 로직 추가**
- Closed #216 
- `SignupExtraInfoRequest`에 생년월일이 오늘 이후의 날짜일 경우 예외 처리하도록 검증 로직 추가(`isValidBirthday`메서드)
- 오늘 날짜로 회원 가입을 할 경우(성공), 내일 날짜로 회원 가입을 할 경우(실패)를 나눠 테스트 코드 진행
- `MemberController`가 FileService 인터페이스가 아닌 구현체를 참조하고 있어 해당 부분을 수정 하였습니다
`private final FileServiceImpl fileService;` -> `private final FileService fileService;`
.
> [Fix] 미래의 생년월일 회원가입 안되도록 검증 로직 추가 #216

- build.gradle
- src/main/java/com/palbang/unsemawang/common/util/saju/SajuCalculator.java
- src/main/java/com/palbang/unsemawang/fortune/entity/FortuneUserInfo.java
- src/main/java/com/palbang/unsemawang/fortune/service/FortuneUserInfoRegisterService.java
- src/main/java/com/palbang/unsemawang/fortune/service/FortuneUserInfoUpdateService.java
**사주 정보 저장 및 수정 시 일주 정보 갱신**
- #219 
사주 정보 저장 및 수정 시 일간/일지를 계산해 저장하는 로직 추가
(추가 설명) 
- 양/음력 변환을 위해 KoreanLunarCalendar 라이브러리에 대한 의존성을 추가하였습니다
- `SajuCalcurator` 클래스 추가 - 오행 정보를 계산하기 위한 클래스로, 현재는 일간/일지를 계산하는 메서드와 음력 날짜를 양력으로 변환하는 메서드를 구현해 놓은 상태입니다
- `FortunUserInfo` 엔티티에 `updateDayGanZhiFromBirthday()` 메서드 추가 - SajuCalcurator에서 제공하는 메서드를 통해 일간 및 일지 필드 값을 변경하는 메서드입니다
.
- 추후에 음력 날짜를 양력으로 변환하는 메서드를 별도 클래스로 분리하겠습니다
- 오행 관련 enum 타입이 업로드 되는 대로 해당 타입을 일주/일지 계산 메서드의 반환 타입으로 변경할 예정입니다
> [Feature] 사주 정보 저장 및 수정 시 일주 정보 갱신  #219

- src/main/java/com/palbang/unsemawang/chat/constant/SendType.java
- src/main/java/com/palbang/unsemawang/chat/constant/SenderType.java
- src/main/java/com/palbang/unsemawang/chat/controller/ChatHistoryReadController.java
- src/main/java/com/palbang/unsemawang/chat/controller/ChatRoomReadController.java
- src/main/java/com/palbang/unsemawang/chat/dto/response/ChatHistoryReadResponse.java
- src/main/java/com/palbang/unsemawang/chat/dto/response/ChatMessageResponse.java
- src/main/java/com/palbang/unsemawang/chat/dto/response/ChatRoomReadResponse.java
**채팅방 목록 조회, 채팅 내역 조회 API 명세 작업**
- Closed #236 
- 채팅방 목록 조회, 채팅 내역 조회를 위한 DTO 추가
- 채팅방 목록 조회, 채팅 내역 조회 API 컨트롤러단 추가 및 명세 작업
.
- 현재는 프론트와의 병렬작업을 위한 껍데기 API로 빈 리스트를 반환하도록 했습니다
> [Feature] 채팅방 목록 조회, 채팅 내역 조회 API 명세 작업 #236

- src/main/java/com/palbang/unsemawang/chat/controller/ChatHistoryReadController.java
- src/main/java/com/palbang/unsemawang/chat/dto/response/ChatMessageResponse.java
- src/main/java/com/palbang/unsemawang/chemistry/controller/RecommendController.java
**채팅내역조회, 궁합추천 API 잘못된 응답 수정*
- Closed #242 
- 채팅 내역 조회 API에서 ChatHistortyResponse 객체가 단일 데이터로 응답되어야 하는데 List에 담겨져 응답하고 있어 이를 수정하였습니다
- 궁합 추천 API에서 응답은 제대로 리스트 형태로 가고 있으나, 스웨거 스키마에 단일 데이터로 표시되는 문제가 있어 해당 문제를 일으키는 속성값을 제거하였습니다
- 추가로 ChatMessageResponse에 잘못된 어노테이션을 사용하고 있는 부분을 찾아 해결하였습니다(`JsonAlias` -> `JsonProperty`)
.
.
> [Fix] 채팅내역조회, 궁합추천 API 잘못된 응답 수정 #242

- src/main/java/com/palbang/unsemawang/common/constants/ResponseCode.java
- src/main/java/com/palbang/unsemawang/fortune/controller/FortuneUserInfoRegisterController.java
- src/main/java/com/palbang/unsemawang/fortune/repository/FortuneUserInfoRepository.java
- src/main/java/com/palbang/unsemawang/fortune/service/FortuneUserInfoDeleteService.java
- src/main/java/com/palbang/unsemawang/fortune/service/FortuneUserInfoRegisterService.java
- src/main/java/com/palbang/unsemawang/fortune/service/FortuneUserInfoUpdateService.java
- src/test/java/com/palbang/unsemawang/fortune/controller/FortuneInfoRegisterControllerTest.java
- 사주 정보 CUD 검증 추가 
- #221 
- "본인" 관계인 사주 정보는 "가족, 지인"등의 관계로 변경할 수 없게 검증을 추가
- 또한 "본인" 관계인 사주정보는 회원당 1개만 존재해야함
- 검증 추가 로직만 추가
> [Fix] 사주 정보 CUD 검증 추가 #221

- src/main/java/com/palbang/unsemawang/common/constants/ResponseCode.java
- src/main/java/com/palbang/unsemawang/community/constant/CommunityCategory.java
- src/main/java/com/palbang/unsemawang/community/constant/CommunityListCategory.java
- src/main/java/com/palbang/unsemawang/community/service/PostService.java
- "운세공유게시판" 카테고리 추가
- #246 
- 운세 공유 게시판 카테고리를 추가
- 운세 공유 게시판은 조회, 삭제, 댓글CRUD만 가능
- 수정은 불가능
- 게시글 수정 서비스에서 커뮤니티 카테고리가 "SHARE_FORTUNE_BOARD"이면 수정 불가능하게 검증 추가
- FE분과 상의 후 운세 공유 게시판은 수정하지 못하게 했습니다.
> [Feat] 커뮤니티: "운세공유게시판" 카테고리 추가 #246

- src/main/java/com/palbang/unsemawang/activity/aop/ActivityTraceAspect.java
- src/main/java/com/palbang/unsemawang/activity/aop/NoTracking.java
- src/main/java/com/palbang/unsemawang/activity/controller/ActiveMemberController.java
- src/main/java/com/palbang/unsemawang/activity/entity/ActiveMember.java
- src/main/java/com/palbang/unsemawang/activity/repository/ActiveMemberRepository.java
- src/main/java/com/palbang/unsemawang/activity/service/ActiveMemberService.java
- src/test/java/com/palbang/unsemawang/activity/repository/ActiveMemberRepositoryTest.java
**활동중인 회원 저장 및 조회 서비스 구현**
- Closed #235 
- 활동 회원 정보 redis 엔티티 추가
- 레디스에 활동 회원 정보를 갱신 및 조회하는 서비스 로직 구현
- 회원이 api를 호출하면 활동 회원 리스트에 갱신되도록 Aspect 구현
- 위 aop 작업을 막아야하는 경우를 위해 NoTracking 어노테이션 추가
- 테스트용 횔동 회원 리스트 조회 api 구현(별도 명세 작업은 안했습니다)
.
- 현재 모든 API 호출 시 회원의 활동 정보를 갱신하도록 설정했습니다
- 이를 원하지 않을 경우 컨트롤러 메서드에 `@NoTracking` 어노테이션을 붙여주세요
> [Feature] 활동중인 회원 저장 및 조회 서비스 구현 #235

- src/main/java/com/palbang/unsemawang/chemistry/controller/RecommendControllerImpl.java
- src/main/java/com/palbang/unsemawang/chemistry/repository/MemberMatchingScoreRepository.java
- src/main/java/com/palbang/unsemawang/chemistry/service/RecommendService.java
- src/main/java/com/palbang/unsemawang/common/constants/ResponseCode.java
- 추천 사용자 5명-> 4명
- 추천 사용자 프로필 이미지 변경
- #248 
- 추천 사용자 프로필 이미지가 본인 프로필 이미지가 전달되고 있었는데, 상대방 프로필 이미지로 변경
- 추천 사용자 5명에서 4명으로 수정
> [Fix] 추천 사용자4명, 상대방 프로필 이미지 전달 #248

- src/main/java/com/palbang/unsemawang/activity/aop/ActivityTraceAspect.java
**활동 정보 저장 aop 주석 처리**
- Closed #261 
레디스 연결이 될때까지 api 요청마다 활동 정보를 저장하는 aop 기능을 막아두겠습니다
> [Fix] 활동 정보 저장 aop 주석 처리

- .github/workflows/gradle.yml
**[pr merge 이후에 빌드+배포 되도록 gradle.yml 수정]**
#215
- pr 단계에서의 빌드를 빼고 push 후 빌드+배포 작업 수행하도록 변경
> Refactor: pr merge 이후에 빌드+배포 되도록 gradle.yml 수정

- src/main/java/com/palbang/unsemawang/common/util/redis/RedisHealthCheckController.java
- src/main/java/com/palbang/unsemawang/common/util/redis/RedisHealthCheckService.java
- src/main/java/com/palbang/unsemawang/config/RedisConfig.java
- src/main/resources/application.properties
**[Redis 연결 수정]**
#273
SSL 사용 설정을 통해 ElastiCache와 연결 가능하도록 하였습니다
- RedisConnectionFactory 빈을 추가하여 Lettuce 클라이언트를 통한 Redis 연결을 설정.
- ElastiCache 사용을 위해 SSL 연결을 활성화. (중요)
- Redis 명령어 타임아웃을 5초로 설정하여 응답 지연을 방지.
- RedisStandaloneConfiguration을 사용하여 Redis 서버의 호스트와 포트 설정.
- Redis 서버와의 연결 안정성을 위해 Redis 연결 타임아웃을 3초로 설정하여 네트워크 지연이나 서버 응답 시간에 대한 여유를 추가.
- health-check를 위한 컨트롤러와 서비스 추가
> [Fix] redis 연결 #273

- src/main/java/com/palbang/unsemawang/common/constants/ResponseCode.java
- src/main/java/com/palbang/unsemawang/fcm/controller/FcmController.java
- src/main/java/com/palbang/unsemawang/fcm/dto/request/FcmTokenRegiRequest.java
- src/main/java/com/palbang/unsemawang/fcm/entity/FcmToken.java
- src/main/java/com/palbang/unsemawang/fcm/repository/FcmRepository.java
- src/main/java/com/palbang/unsemawang/fcm/service/FcmService.java
feat:fcm 비활성화 기능 추가 및 조회 수정
- #272 
1.토큰 저장로직 수정
- 새로운 FCM 토큰 저장시 활성화(isActive => false->true)
- 저장시 해당 토큰으로 조회 비활성화된 코드가 존재한다면 활성화(isActive => false->true)
2.토큰 조회 수정 및 비활성화 추가
- 회원 토큰 조회 수정
- 회원 해당 토큰 조회후 비활성화 기능 추가
3.엔티티 수정
- DeviceType, BrowserType 값 필수 => 필수X
- isActive 활성여부 추가
- expiresAt 만료기한 추가
4.ResponseCode 추가
- INVALID_FCM_TOKEN("6138",HttpStatus.BAD_REQUEST, "해당 FCM 토큰은 해당 회원의 것이 아닙니다."),
- NOT_EXIST_ACTIVE_FCM_TOKEN("6226", HttpStatus.BAD_REQUEST, "활성화된 FCM 토큰이 존재하지 않습니다."),
> feat:fcm 비활성화 기능 추가 및 조회 수정

- src/main/java/com/palbang/unsemawang/activity/controller/ActiveStatusWebSocketController.java
- src/main/java/com/palbang/unsemawang/activity/service/ActiveMemberService.java
- src/main/java/com/palbang/unsemawang/chat/dto/NewChatMessageCountDto.java
- src/main/java/com/palbang/unsemawang/chat/dto/NewChatMessageDto.java
- src/main/java/com/palbang/unsemawang/chat/entity/ChatRoom.java
- src/main/java/com/palbang/unsemawang/chat/service/ChatMessageConsumer.java
**채팅방 리스트를 보고 있을 경우 새로운 메세지 핸들링**
- #296 
1. 새로운 메세지 내용, 새로운 메세지 개수를 전달하기 위한 DTO를 각각 만들었습니다
2. ChatMessageConsumer 클래스의 consumeMessage 메서드에 다음과 같은 로직을 추가하였습니다
- 채팅 상대가 채팅방 리스트를 보고 있을 경우 새로운 메세지를  알림
채널: /topic/chat/{chatRoomId}/{memberId}/new-message
- 채팅 상대가 채팅방 리스트를 보고 잇을 경우 읽지 않은 메세지 개수를 알림
채널: : /topic/chat/{chatRoomId}/{memberId}/new-message/count
- 추가로 메서드 전체를 감싸고 있던 catch문은 예외 로그를 알기가 어려워 임시 주석 처리 했습니다
- 상태 정보 변경 메세지가 전달된 경우 세션 헤더로부터 인증 정보를 가져오도록 수정하였습니다
- 현재 안읽은 메세지 전달할 떄 잘 맞지 않는 오류가 있습니다..해결하면 바로 올릴게욥~
> [Feature] 채팅방 리스트를 보고 있을 경우 새로운 메세지 핸들링 #296

- src/main/java/com/palbang/unsemawang/config/WebConfig.java
- src/main/java/com/palbang/unsemawang/fcm/controller/FcmController.java
- src/main/java/com/palbang/unsemawang/fcm/service/FcmService.java
1. 회원 fcm 토큰값 없을시 빈 배열 리턴하도록 수정
2. fcm 메세지 요청시 api 수정
3. webConfig 수정(allowedMethod -"PATCH", "OPTIONS" 추가)
- #272 
1. 회원 fcm 토큰값 없을시 빈 배열 리턴하도록 수정
2. fcm 메세지 요청시 api 수정
3. webConfig 수정(allowedMethod -"PATCH", "OPTIONS" 추가)
> [Fix]: fcm 관련 수정 및 webConfig 수정

- src/main/java/com/palbang/unsemawang/chat/dto/ChatRoomDto.java
- src/main/java/com/palbang/unsemawang/chat/service/ChatRoomService.java
[Fix] 채팅방 목록 성별 수정
#318
1. 채팅방 목록 조회 시 성별이 모두 '여'로 나오던 버그 수정
```java
// 채팅방 아이디와 회원 아이디로 상대 회원 객체 생성
Member targetUser = getTargetUser(chatRoom, userId)
.orElseThrow(() -> new GeneralException(ResponseCode.NOT_EXIST_MEMBER_ID));
// 상대 회원 아이디로 사주 정보 객체 생성 후 성별 조회
FortuneUserInfo fortuneUserInfo = fortuneUserInfoRepository.findByMemberIdRelationIdIsOne(
targetUser.getId())
.orElseThrow(() -> new GeneralException(ResponseCode.ERROR_SEARCH));
char sex = fortuneUserInfo.getSex();
```
> [Fix] 채팅방 목록 성별 수정

- src/main/java/com/palbang/unsemawang/chat/service/ChatMessageConsumer.java
**새로운 메세지 전달 방식 수정 **
- Closed #322 
- 새로운 메세지를 처리할 때 상대방의 활동 상태 상관 없이 무조건 new-message 채널을 구독한 클라이언트에게 새로운 메세지 내용과 안본 메세지 수를 다 보내도록 수정
.
> [Fix] 새로운 메세지 전달 방식 수정 #322

- build.gradle
- src/main/java/com/palbang/unsemawang/community/dto/request/PostRegisterRequest.java
- src/main/java/com/palbang/unsemawang/community/service/CommentService.java
- src/main/java/com/palbang/unsemawang/community/validation/NoHtml.java
- src/main/java/com/palbang/unsemawang/community/validation/NoHtmlValidator.java
- 운세 공유 게시판 html 태그 등록 불가 검증 추가
- 운세 공유 게시판일 때 댓글 조회 가능하게 수정
- #305 
- build.gradle 의존성 추가
- 익명 게시판과 자유 게시판을 if - else if로 분기 처리했는데 if-else로 변경
- html 검증 애너테이션 추가 ( h3, p 태그는 예외)
> [Fix] 운세 공유 게시판 html 태그 등록 불가 검증 추가 #305

- src/main/java/com/palbang/unsemawang/chat/entity/ChatRoom.java
- src/main/java/com/palbang/unsemawang/chat/service/ChatRoomService.java
[Fix] 채팅방 생성 로직 수정
#311 
1. `createOrGetChatRoom` 메서드로 채팅방 생성 시 기존 채팅방이 존재하는지 확인하고 생성하는 로직 삭제
- 채팅방 중복 생성이 가능합니다
> [Fix] 채팅방 생성 로직 수정

- src/main/java/com/palbang/unsemawang/config/FirebaseConfig.java
fcmCofing 수정
- #330 
fcm 메시지 요청 보낼시 자주 오류(Caused by: org.apache.hc.core5.http.ProtocolException: Header 'Host: fcm.googleapis.com' is illegal for HTTP/2 messages)가 발생하였음
HTTP/2 => HTTP/1.1 // HTTP/1.1을 사용하도록 NetHttpTransport 적용
주요 변경된 코드나 함수, 클래스, 모듈에 대해 설명해 주세요. 변경 사항이 중요한 부분이라면 코드와 함께 설명을 추가해주세요.
> [Fix] 메시지 안보내지는 오류 수정

- src/main/java/com/palbang/unsemawang/activity/entity/ActiveMember.java
- src/main/java/com/palbang/unsemawang/activity/service/ActiveMemberService.java
- src/main/java/com/palbang/unsemawang/config/CacheConfig.java
- src/main/java/com/palbang/unsemawang/config/SchedulerConfig.java
- src/main/java/com/palbang/unsemawang/member/entity/Member.java
- src/main/java/com/palbang/unsemawang/member/service/MemberActiveScheduler.java
- src/main/java/com/palbang/unsemawang/member/service/MemberActivityService.java
**마지막 활동 시간 갱신 스케줄러 적용 #**
- Closed #303 
- 특정 회원의 활동 상태를 조회할 때 @Cacheable 어노테이션을 이용해 자동으로 레디스에서 읽어오도록 하고, 조회 결과가 없을 경우 DB에서 읽어와 반환하도록 수정하였습니다
- 5분마다 레디스에 저장된 회원 활동 상태를 읽어 새로 업데이트된 경우 DB에 마지막 활동 시간을 갱신하도록 스케줄러 메서드를 추가했습니다
- 활동 상태 레디스 엔티티에 TTL(Time To Live) 시간을 3시간으로 설정하고,
- DB에 저장됐는지 구분하기 위해 isSaved 필드를 추가했습니다
> [Feature] 마지막 활동 시간 갱신 스케줄러 적용 #303
